cart
sofia2123ewwr/my-shop pull request #1
Opened 2023-02-07 16:06 UTC by sofia2123ewwr

2023-02-08 21:28 UTC, loqimean requested changes

2023-02-08 21:28 UTC, loqimean commented on Gemfile
> +gem 'rails_admin'
ніт, видаляй то)

2023-02-08 21:28 UTC, loqimean commented on Gemfile
>  gem "cssbundling-rails"
а це тобі навіщо?)

2023-02-08 21:28 UTC, loqimean commented on app/views/home/index.html.erb
>  </div>
нова строка

2023-02-08 21:28 UTC, loqimean commented on app/views/layouts/_cart_add.html.erb
> +<% if  @cart_product = CartProduct.new %>
що це таке?)) кароч, подивись запис мітингу експертського, перший наче, я там говорив про те, що інстанс змінні ми не юзаємо у паршалаї + що це за перевірка така?) видаляй то)

2023-02-08 21:28 UTC, loqimean commented on app/views/layouts/_footer.html.erb
>          <button type="button" class="inline-block px-6 py-2 border-2 border-white text-white font-medium text-xs leading-tight uppercase rounded-full hover:bg-neutral-800 hover:bg-orange-600 focus:ou
компонента

2023-02-08 21:28 UTC, loqimean commented on app/views/layouts/_footer.html.erb
> +              <%= link_to cart_path(@current_cart) do %>
у футері?

2023-02-08 21:28 UTC, loqimean commented on app/views/layouts/_footer.html.erb
> +              <%= link_to cart_path(@current_cart) do %>
та і що, якщо карта нема, бо юзер не авторизований?

2023-02-08 21:28 UTC, loqimean commented on app/views/layouts/_header.html.erb
> +        <div class="inline-block px-6 py-2.5 bg-black text-orange-600 font-medium text-xs leading-tight uppercase rounded shadow-md hover:bg-white hover:shadow-lg focus:bg-white focus:shadow-lg focus
компонента

2023-02-08 21:28 UTC, loqimean commented on app/views/layouts/_header.html.erb
> +            <button type="button" class="inline-block px-6 py-2.5 mr-2 bg-transparent text-black font-medium text-xs leading-tight uppercase rounded hover:text-orange-600 hover:bg-gray-100 focus:bg-g
компонента

2023-02-08 21:28 UTC, loqimean commented on app/views/layouts/_header.html.erb
> +          <div class="inline-block px-6 py-2.5 mr-2 bg-transparent text-black font-medium text-xs leading-tight uppercase rounded hover:text-orange-600 hover:bg-gray-100 focus:bg-gray-100 focus:outli
компонента

2023-02-08 21:28 UTC, loqimean commented on spec/helpers/categories_helper_spec.rb
> +end
видаляй файли, якщо не юзаєш їх

2023-02-08 21:28 UTC, loqimean commented on spec/requests/carts_spec.rb
> +      get "/carts/destroy"
якщо це ріл тести, що ти писала, то тут треба роут хелпер юзати

2023-02-08 21:28 UTC, loqimean commented on spec/requests/product_spec.rb
> +end
говорив

2023-02-08 21:28 UTC, loqimean commented on yarn.lock
> +  integrity sha512-gt3PKXs0DBoL9xCvOIIZ2NEqAGZqHjAnmVbfQtB620V0uReIQutpel14KcneZuer7UioY8ALKZ7iocavvzTNFA==
а це що таке і навіщо?)

2023-02-08 21:28 UTC, loqimean commented on package.json
> +    "build:css": "sass ./app/assets/stylesheets/rails_admin.scss:./app/assets/builds/rails_admin.css --no-source-map --load-path=node_modules"
видаляй

2023-02-08 21:28 UTC, loqimean commented on db/seeds.rb
> +    Product.create!(name: name, price: price, description: description, position: position, category_id: category_id)
а факторі тобі навіщо?)

2023-02-08 21:28 UTC, loqimean commented on db/seeds.rb
> +    Product.create!(name: name, price: price, description: description, position: position, category_id: category_id)
з оцього всього має бути.., 10 строк коду, не враховуючи коментів та нових строк. НЕ БІЛЬШЕ 10

2023-02-08 21:28 UTC, loqimean commented on db/migrate/20230207143849_create_orders.rb
> +      t.string :status
а де дефолт?)

2023-02-08 21:28 UTC, loqimean commented on db/migrate/20230207143238_create_addresses.rb
> +      t.text :comment
тобто ми можемо створити адресу без нічого?)

2023-02-08 21:28 UTC, loqimean commented on db/migrate/20230201203135_create_products.rb
> +      t.string :name
тобто ми можемо створити продукт без назви?)

2023-02-08 21:28 UTC, loqimean commented on db/migrate/20230201203135_create_products.rb
> +       t.decimal :price
а де дефолтна ціна?)

2023-02-08 21:28 UTC, loqimean commented on db/migrate/20230201203135_create_products.rb
> +      t.integer :position
а де дефолт?)

2023-02-08 21:28 UTC, loqimean commented on db/migrate/20230201202001_create_categories.rb
> +      t.text :name
категорія без нейма?)

2023-02-08 21:28 UTC, loqimean commented on db/migrate/20230201202001_create_categories.rb
> +      t.integer :position
а де дефолт?)

2023-02-08 21:28 UTC, loqimean commented on db/migrate/20230201142521_add_admin_to_user.rb
> +    add_column :users, :is_admin, :boolean, default: false
є така штука, як `enum` ))

2023-02-08 21:28 UTC, loqimean commented on config/routes.rb
> +  get '/categories', to: 'caregories#show'
міняй

2023-02-08 21:28 UTC, loqimean commented on config/importmap.rails_admin.rb
> +pin "jquery-ui/", to: "https://ga.jspm.io/npm:jquery-ui@1.13.2/"
нова строка

2023-02-08 21:28 UTC, loqimean commented on config/importmap.rails_admin.rb
> +pin "jquery-ui/", to: "https://ga.jspm.io/npm:jquery-ui@1.13.2/"
видаляй

2023-02-08 21:28 UTC, loqimean commented on config/importmap.rails_admin.rb
> +pin "bootstrap", to: "https://ga.jspm.io/npm:bootstrap@5.2.3/dist/js/bootstrap.esm.js"
який у нас стек проекту?)

2023-02-08 21:28 UTC, loqimean commented on config/importmap.rails_admin.rb
> +pin "rails_admin/src/rails_admin/base", to: "https://ga.jspm.io/npm:rails_admin@3.1.1/src/rails_admin/base.js"
видаляй і що це за назва така файлу?

2023-02-08 21:28 UTC, loqimean commented on app/views/products/index.html.erb
> +            <%= button_to "Add to cart", cart_product_path(:product_id => product.id), class:"h-10 px-6 font-semibold rounded-md bg-black text-white" %>
карт_продукт_паз? це що таке ще?

2023-02-08 21:28 UTC, loqimean commented on app/views/products/index.html.erb
> +            <%= button_to "Add to cart", cart_product_path(:product_id => product.id), class:"h-10 px-6 font-semibold rounded-md bg-black text-white" %>
```suggestion
            <%= button_to "Add to cart", cart_product_path(product_id: product.id), class:"h-10 px-6 font-semibold rounded-md bg-black text-white" %>
```

2023-02-08 21:28 UTC, loqimean commented on app/views/products/index.html.erb
> +<%# render 'layouts/cart_add'%>
а це навіщо тут?

2023-02-08 21:28 UTC, loqimean commented on app/views/products/index.html.erb
> +<h1 class="text-center my-10 text-5xl md:text-6xl xl:text-7xl text-orange-600 font-bold mb-12">All products</h1>
компонента

2023-02-08 21:28 UTC, loqimean commented on app/views/orders/show.html.erb
> +</div>
а це навіщо тут?

2023-02-08 21:28 UTC, loqimean commented on app/views/orders/new.html.erb
> +<%= form_for(@order) do |f| %>
я казав, ми юзаємо сімпл_форм)

2023-02-08 21:28 UTC, loqimean commented on app/views/orders/new.html.erb
> +<%= form_for(@order) do |f| %>
навіть посилання дав)

2023-02-08 21:28 UTC, loqimean commented on app/views/orders/new.html.erb
> +  <p>
чому в параграфі?

2023-02-08 21:28 UTC, loqimean commented on app/views/products/_product.html.erb
> +        </label>
хелпери

2023-02-08 21:28 UTC, loqimean commented on app/views/products/_product.html.erb
> +          <div class="rounded-lg flex items-center justify-center text-slate-700 peer-checked:font-semibold peer-checked:bg-slate-900 peer-checked:text-white">
компонента

2023-02-08 21:28 UTC, loqimean commented on app/views/products/_product.html.erb
> +<section class="max-w-6xl mx-auto px-4 sm:px-6 lg:px-4 py-12 border-4 border-x-white border-y-black">
компонента

2023-02-08 21:28 UTC, loqimean commented on app/views/layouts/_header.html.erb
> +        <a class=" w-10 h-10 navbar-brand text-black" href="https://market.rukavychka.ua/">
хелпер))

2023-02-08 21:28 UTC, loqimean commented on app/views/layouts/_header.html.erb
> +  <nav class="testclass absolute navbar navbar-expand-lg shadow-md py-2 bg-orange-600 relative flex items-center w-full justify-between">
компонент)

2023-02-08 21:28 UTC, loqimean commented on app/views/devise/sessions/new.html.erb
> +        <div class="actions inline-block px-6 py-2.5 bg-black text-orange-600 font-medium text-xs leading-tight uppercase rounded shadow-md hover:bg-white hover:shadow-lg focus:bg-white focus:shadow-
компонента)

2023-02-08 21:28 UTC, loqimean commented on app/views/devise/registrations/new.html.erb
> +</div>
нова строка

2023-02-08 21:28 UTC, loqimean commented on app/views/devise/registrations/new.html.erb
> +        <button type="submit" class="inline-block mt-10 px-6 py-2.5 bg-black text-orange-600 font-medium text-xs leading-tight uppercase rounded shadow-md hover:bg-white hover:shadow-lg focus:bg-whit
компонента

2023-02-08 21:28 UTC, loqimean commented on app/views/categories/_category_id.html.erb
> +</div>
нова строка

2023-02-08 21:28 UTC, loqimean commented on app/views/categories/_category_id.html.erb
> +    <button class=" mx-10 inline-block px-6 py-2.5 bg-black text-orange-600 font-medium text-xs leading-tight uppercase rounded shadow-md hover:bg-white hover:shadow-lg focus:bg-white focus:shadow-lg
компонента, і хелпер

2023-02-08 21:28 UTC, loqimean commented on app/views/categories/_category_id.html.erb
> +  <% Category.all.each do |category| %>
для чого у нас поле `position`?)

2023-02-08 21:28 UTC, loqimean commented on app/views/categories/_category_id.html.erb
> +<%# i know its not good, but i dont know why @categories dont work %>
не працює тут інстанс змінна, БО Я НЕ ПРОСТО ТАК КАЗАВ ЇХ НЕ ЮЗАТИ В ПАРШАЛАХ)

2023-02-08 21:28 UTC, loqimean commented on app/views/carts/show.html.erb
> +        </button>
хеееелпер

2023-02-08 21:28 UTC, loqimean commented on app/views/carts/show.html.erb
> +        <button class="mt-6 w-full rounded-md bg-orange-600 py-1.5 font-medium text-black hover:bg-gray-200">
компонента

2023-02-08 21:28 UTC, loqimean commented on app/views/carts/show.html.erb
> +        </button>
again..

2023-02-08 21:28 UTC, loqimean commented on app/views/carts/show.html.erb
> +      <% @cart.cart_products.each do |cart_product| %>
міняй

2023-02-08 21:28 UTC, loqimean commented on app/models/order.rb
> +  has_many :product_orders
а якщо я видалю ордер, то що? будемо засмічувати БД?

2023-02-08 21:28 UTC, loqimean commented on app/models/cart.rb
> +    return sum
SQL і ретурн писати в рубі не треба, він сам повертає останнє значення

2023-02-08 21:28 UTC, loqimean commented on app/javascript/rails_admin.js
> +import "rails_admin/src/rails_admin/base";
видаляй

2023-02-08 21:28 UTC, loqimean commented on app/helpers/products_helper.rb
> +module ProductsHelper
видаляй пусті файли

2023-02-08 21:28 UTC, loqimean commented on app/assets/stylesheets/rails_admin.scss
> +@import "rails_admin/src/rails_admin/styles/base";
видаляй

2023-02-08 21:28 UTC, loqimean commented on app/controllers/application_controller.rb
> +  before_action :initalize_cart
а якщо я на сторінці "про нас"?

2023-02-08 21:28 UTC, loqimean commented on app/controllers/application_controller.rb
> +      if current_user.cart.present?
не доцільно робити цю перевірку міліони разів, якщо можна відразу після створення юзера задавати йому корзину

2023-02-08 21:28 UTC, loqimean commented on app/controllers/application_controller.rb
> +      end
відколи ми зберігаємо рекорд БД у сешені?)

2023-02-08 21:28 UTC, loqimean commented on app/controllers/cart_products_controller.rb
> +class CartProductsController < ApplicationController
цього контроллера не повинно бути

2023-02-08 21:28 UTC, loqimean commented on app/controllers/carts_controller.rb
> +    @cart = @current_cart
і звідки ж ти береш той карент карт?)

2023-02-08 21:28 UTC, loqimean commented on app/controllers/carts_controller.rb
> +  # end
видаляй

2023-02-08 21:28 UTC, loqimean commented on app/controllers/categories_controller.rb
> +    @category = Category.find(params[:id])
ресурс?)

2023-02-08 21:28 UTC, loqimean commented on app/controllers/categories_controller.rb
> +    end
видаляй

2023-02-08 21:28 UTC, loqimean commented on app/controllers/products_controller.rb
> +    @products = Product.all
колекшин

2023-02-08 21:28 UTC, loqimean commented on app/controllers/products_controller.rb
> +  private
```suggestion
  private

```

2023-02-08 21:28 UTC, loqimean commented on app/controllers/users/sessions_controller.rb
> +    return if session[:cart_id].blank?
шо?)

2023-02-08 21:28 UTC, loqimean commented on app/models/user.rb
> +  has_one :cart
ну а от я видалив юзера, що далі?

2023-02-08 21:28 UTC, loqimean commented on app/views/carts/show.html.erb
> +  <h1 class="text-center my-10 text-5xl md:text-6xl xl:text-7xl text-orange-600 font-bold mb-12">Cart</h1>
компонента

2023-02-08 21:28 UTC, loqimean commented on app/views/carts/show.html.erb
> +    <% @cart.cart_products.each do |cart_product| %>
це що таке?

2023-02-08 21:28 UTC, loqimean commented on app/controllers/orders_controller.rb
> +    @orders = Order.all
колекшин

2023-02-08 21:28 UTC, loqimean commented on app/controllers/orders_controller.rb
> +    @order = Order.find(params[:id])
ресурс

2023-02-08 21:28 UTC, loqimean commented on app/controllers/orders_controller.rb
> +    end
міняй, я сьогодні показував, як то зробити гарно

2023-02-08 21:28 UTC, loqimean commented on app/controllers/orders_controller.rb
> +    @order.save
а якщо не збереже?

2023-02-08 21:28 UTC, loqimean commented on app/controllers/orders_controller.rb
> +    Cart.destroy(session[:cart_id])
ну і навіщо?

2023-02-08 21:28 UTC, loqimean commented on app/controllers/orders_controller.rb
> +    session[:cart_id] = nil
а це ще що таке?

2023-02-08 21:28 UTC, loqimean commented on app/controllers/orders_controller.rb
> +  private
```suggestion
  private

```

2023-02-08 21:28 UTC, loqimean commented on config/initializers/rails_admin.rb
> +    ## With an audit adapter, you can add:
видаляємо)

2023-02-10 12:59 UTC, sofia2123ewwr commented on app/views/layouts/_footer.html.erb
> +              <%= link_to cart_path(@current_cart) do %>
в мене в Application і для авторизованих і не авторизованих це прописано

2023-02-10 13:05 UTC, sofia2123ewwr commented on db/migrate/20230201203135_create_products.rb
> +       t.decimal :price
а нащо нам дефолтна ціна?
це ознаа, що треба поставити нал фолс

2023-02-10 13:45 UTC, sofia2123ewwr commented on app/controllers/carts_controller.rb
> +    @cart = @current_cart
з application

2023-02-24 08:44 UTC, sofia2123ewwr commented on db/seeds.rb
> +    Product.create!(name: name, price: price, description: description, position: position, category_id: category_id)
i did it

2023-02-24 08:44 UTC, sofia2123ewwr commented on config/routes.rb
> +  get '/categories', to: 'caregories#show'
changed

2023-02-25 08:54 UTC, sofia2123ewwr commented on app/views/products/index.html.erb
> +            <%= button_to "Add to cart", cart_product_path(:product_id => product.id), class:"h-10 px-6 font-semibold rounded-md bg-black text-white" %>
delete

2023-02-25 08:59 UTC, sofia2123ewwr commented on app/controllers/orders_controller.rb
> +    session[:cart_id] = nil
changed

2023-02-25 09:06 UTC, sofia2123ewwr commented on app/controllers/users/sessions_controller.rb
> +    return if session[:cart_id].blank?
Метод link_cart_to_user перевіряє, чи зберігається cart_id у сеансі. Якщо є, він знаходить відповідний об’єкт Cart і оновлює його поточним_користувачем за допомогою методу update.
це пгана ідея?

2023-02-25 09:33 UTC, merged